### ISSUE TITLE
Improve Event log to get statistics

### ISSUE THREAD

**Issue by rzulian** [boardgamers/gaia-engine#159]
If we want to use logs to get statistics, we need to improve current log implementation:

- [ ] specify what's has been build in `build`
- [ ] replace `roundX` with the scoring tile booster (e.g.  `Score6`)
- [ ] specify the research area in `up` (e.g. `up gaia`)
- [ ] list the full `income`
- [ ] add gaiaform build
- [ ] add income for lab (e.g. `tech xxx` `up yyy`), where techs are the effective tiles , not the position

TBC

**Comment by coyotte508** [comment]
I specifically changed the scoreX to roundX because it was much better in the logs. And also if we add a tally of VP earned through the game for each player, it will display much nicer.

That doesn't mean we can't do stats based on scoring tile booster, we can easily deduce it by matching roundX with the booster of roundX.

We should probably also add a statistics object in the game model in gaia-site.

**Comment by rzulian** [comment]
Trust me, I have been doing business intelligence for almost 20 years. It's better to have better raw data, and work on the presentation, that do the opposite ;)

**Comment by coyotte508** [comment]
Doesn't bother me, as long as we do both at the same time.

**Comment by coyotte508** [comment]
Actually, the problem with tech tiles is similar (tech-gaia / techX). It would make sense to have both data stored (friendly name & raw tech / scoring tile).
